// packages/ui/src/components/avatar.tsx
'use client'

import * as React from 'react'
import * as AvatarPrimitive from '@radix-ui/react-avatar'

import { cn } from '@fintech/utils'

function Avatar({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Root>) {
  return (
    <AvatarPrimitive.Root
      data-slot="avatar"
      className={cn(
        'relative flex size-8 shrink-0 overflow-hidden rounded-full',
        className,
      )}
      {...props}
    />
  )
}

function AvatarImage({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Image>) {
  return (
    <AvatarPrimitive.Image
      data-slot="avatar-image"
      className={cn('aspect-square size-full', className)}
      {...props}
    />
  )
}

function AvatarFallback({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn(
        'bg-muted flex size-full items-center justify-center rounded-full',
        className,
      )}
      {...props}
    />
  )
}

export { Avatar, AvatarImage, AvatarFallback }

// apps/web/src/app/shared/components/avatar/avatar.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-avatar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      [class]="'relative flex size-8 shrink-0 overflow-hidden rounded-full ' + (className || '')"
    >
      <ng-content></ng-content>
    </div>
  `,
  styles: []
})
export class AvatarComponent {
  @Input() className?: string;
}

@Component({
  selector: 'app-avatar-image',
  standalone: true,
  imports: [CommonModule],
  template: `
    <img
      [src]="src"
      [alt]="alt"
      [class]="'aspect-square size-full ' + (className || '')"
    />
  `,
  styles: []
})
export class AvatarImageComponent {
  @Input() src?: string;
  @Input() alt?: string;
  @Input() className?: string;
}

@Component({
  selector: 'app-avatar-fallback',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      [class]="'bg-muted flex size-full items-center justify-center rounded-full ' + (className || '')"
    >
      <ng-content></ng-content>
    </div>
  `,
  styles: []
})
export class AvatarFallbackComponent {
  @Input() className?: string;
}
